# application.yaml
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8010/eureka/,http://eureka-secondary:8010/eureka/,http://eureka-tertiary:8010/eureka/
  instance:
      metadataMap:
        instanceId: ${spring.application.name}:${server.port}
---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog  